"""
player_form_data.py — Supplemental 2026 pre-Masters player data.

RANKING_CHANGE_60D  : World ranking change over the last 60 days (positive = improving,
                      e.g. +12 means moved from #22 to #10).
SG_APP_90D          : SG Approach strokes-gained average over the last 90 days.
                      Separates sustained iron quality from season-long regression.
SUNDAY_SCORING_DIFF : Final-round scoring differential vs field average over last
                      12 months (negative = better than field, -1.8 → 1.8 strokes better).
"""
from __future__ import annotations

# ─────────────────────────────────────────────────────────────────
# WORLD RANKING CHANGE — LAST 60 DAYS
# Positive = rank number fell (improved), Negative = rank rose (declined)
# ─────────────────────────────────────────────────────────────────
RANKING_CHANGE_60D: dict[str, int] = {
    "Scottie Scheffler":          0,   # WR#1; stable, dominant
    "Rory McIlroy":              -3,   # WD Arnold Palmer (back), T46 Players — form dip
    "Xander Schauffele":         +4,   # T3 Players, T4 Valspar — consistent top-5s
    "Collin Morikawa":           -8,   # Back injury; no competitive play since March 12
    "Ludvig Aberg":              +5,   # Consistent top-5s
    "Jon Rahm":                  +8,   # Won HK, 3 runners-up, T5 Singapore — dominant LIV form
    "Bryson DeChambeau":         +12,  # 2 consecutive LIV wins — hottest player in world golf
    "Brooks Koepka":              0,
    "Viktor Hovland":            +7,
    "Patrick Cantlay":           +3,
    "Tony Finau":                +4,
    "Justin Thomas":             -3,
    "Tommy Fleetwood":           +6,   # T8 Players, T10 Valero; 4 top-10s in 5 starts
    "Cameron Young":             +8,   # Won The Players; strong form entering Augusta
    "Hideki Matsuyama":          -1,
    "Shane Lowry":               +3,
    "Dustin Johnson":            -5,
    "Phil Mickelson":            -9,
    "Tiger Woods":               -5,
    "Sahith Theegala":           +12,
    "Russell Henley":            +6,
    "Keegan Bradley":            +3,
    "Max Homa":                  +2,
    "Will Zalatoris":            -4,
    "Si Woo Kim":                +5,
    "Matt Fitzpatrick":          +5,   # Won Valspar 2026; consistent Augusta record
    "Adam Scott":                -7,
    "Corey Conners":             +4,
    "Tyrrell Hatton":            -2,
    "Tom Kim":                   +8,
    "Sepp Straka":               +3,
    "Min Woo Lee":               +13,
    "Robert MacIntyre":          +7,
    "Sungjae Im":                +2,
    "Harris English":            +5,
    "Lucas Glover":              +1,
    "Nick Taylor":               +4,
    "Akshay Bhatia":             +11,
    "Nicolai Hojgaard":          +6,
    "Davis Riley":                0,
    "Brian Harman":              -3,
    "Jason Day":                 -5,
    "Sergio Garcia":             -4,
    "Adam Hadwin":               +2,
    "Christiaan Bezuidenhout":   +3,
    "Matthieu Pavon":            +5,
    "Joaquin Niemann":           -2,
    "Dean Burmester":            +2,
    "Rasmus Hojgaard":           +4,
    "Thriston Lawrence":         +1,
    "Kurt Kitayama":             +3,
    "Cam Davis":                 +2,
    "J.T. Poston":               +1,
    "Aaron Rai":                 +7,
    "Patrick Reed":              +8,   # Won Dubai Desert Classic + Qatar Masters 2026; in form
    "Zach Johnson":              -6,
    "Fred Couples":              -4,
    "Larry Mize":                -2,
    "José María Olazábal":       -2,
    "Taylor Moore":              +2,
    "Denny McCarthy":            +1,
    "Taylor Pendrith":           +3,
    "Wyndham Clark":             +5,
    "Chris Kirk":                -1,
    "Eric Cole":                 +4,
    "Emiliano Grillo":           +3,
    "Thomas Detry":              +6,
    "Alex Noren":                -2,
    "Ryan Fox":                  +1,
}

# ─────────────────────────────────────────────────────────────────
# SG APPROACH — LAST 90 DAYS
# Isolates recent approach play from full-season regression to mean
# ─────────────────────────────────────────────────────────────────
SG_APP_90D: dict[str, float] = {
    "Scottie Scheffler":         1.48,
    "Rory McIlroy":              0.94,
    "Xander Schauffele":         1.08,
    "Collin Morikawa":           1.42,
    "Ludvig Aberg":              1.15,
    "Jon Rahm":                  0.90,
    "Bryson DeChambeau":         0.76,
    "Brooks Koepka":             0.68,
    "Viktor Hovland":            1.05,
    "Patrick Cantlay":           0.97,
    "Tony Finau":                0.80,
    "Justin Thomas":             1.18,
    "Tommy Fleetwood":           1.22,
    "Cameron Young":             0.84,
    "Hideki Matsuyama":          1.00,
    "Shane Lowry":               0.74,
    "Dustin Johnson":            0.64,
    "Phil Mickelson":            0.60,
    "Tiger Woods":               0.55,
    "Sahith Theegala":           0.90,
    "Russell Henley":            1.10,
    "Keegan Bradley":            0.86,
    "Max Homa":                  0.94,
    "Will Zalatoris":            1.20,
    "Si Woo Kim":                0.80,
    "Matt Fitzpatrick":          1.25,
    "Adam Scott":                0.70,
    "Corey Conners":             1.08,
    "Tyrrell Hatton":            0.92,
    "Tom Kim":                   0.88,
    "Sepp Straka":               0.84,
    "Min Woo Lee":               0.98,
    "Robert MacIntyre":          0.90,
    "Sungjae Im":                0.95,
    "Harris English":            0.76,
    "Lucas Glover":              0.72,
    "Nick Taylor":               0.80,
    "Akshay Bhatia":             0.86,
    "Nicolai Hojgaard":          0.92,
    "Davis Riley":               0.82,
    "Brian Harman":              0.74,
    "Jason Day":                 0.88,
    "Sergio Garcia":             0.70,
    "Adam Hadwin":               0.77,
    "Christiaan Bezuidenhout":   0.82,
    "Matthieu Pavon":            0.90,
    "Joaquin Niemann":           0.78,
    "Dean Burmester":            0.64,
    "Rasmus Hojgaard":           0.85,
    "Thriston Lawrence":         0.80,
    "Kurt Kitayama":             0.74,
    "Cam Davis":                 0.70,
    "J.T. Poston":               0.78,
    "Aaron Rai":                 0.84,
    "Patrick Reed":              0.74,
    "Zach Johnson":              0.64,
    "Fred Couples":              0.50,
    "Larry Mize":                0.44,
    "José María Olazábal":       0.48,
    "Taylor Moore":              0.72,
    "Denny McCarthy":            0.68,
    "Taylor Pendrith":           0.78,
    "Wyndham Clark":             0.90,
    "Chris Kirk":                0.72,
    "Eric Cole":                 0.78,
    "Emiliano Grillo":           0.82,
    "Thomas Detry":              0.88,
    "Alex Noren":                0.72,
    "Ryan Fox":                  0.76,
}

# ─────────────────────────────────────────────────────────────────
# SUNDAY SCORING DIFFERENTIAL vs FIELD AVERAGE
# Average of final-round scores vs field over trailing 12 months.
# Negative = better than field (lower scores). Range roughly -2.5 to +0.5
# ─────────────────────────────────────────────────────────────────
SUNDAY_SCORING_DIFF: dict[str, float] = {
    "Scottie Scheffler":         -2.20,
    "Rory McIlroy":              -1.85,
    "Xander Schauffele":         -1.55,
    "Collin Morikawa":           -1.20,
    "Ludvig Aberg":              -0.85,
    "Jon Rahm":                  -1.95,
    "Bryson DeChambeau":         -1.45,
    "Brooks Koepka":             -1.60,
    "Viktor Hovland":            -1.05,
    "Patrick Cantlay":           -1.35,
    "Tony Finau":                -0.65,
    "Justin Thomas":             -1.50,
    "Tommy Fleetwood":           -1.15,
    "Cameron Young":             -0.90,
    "Hideki Matsuyama":          -1.25,
    "Shane Lowry":               -1.05,
    "Dustin Johnson":            -0.70,
    "Phil Mickelson":            -0.50,
    "Tiger Woods":               -1.80,
    "Sahith Theegala":           -0.80,
    "Russell Henley":            -1.20,
    "Keegan Bradley":            -0.90,
    "Max Homa":                  -1.00,
    "Will Zalatoris":            -1.30,
    "Si Woo Kim":                -0.75,
    "Matt Fitzpatrick":          -0.90,
    "Adam Scott":                -1.10,
    "Corey Conners":             -0.80,
    "Tyrrell Hatton":            -1.15,
    "Tom Kim":                   -0.70,
    "Sepp Straka":               -0.80,
    "Min Woo Lee":               -0.90,
    "Robert MacIntyre":          -0.85,
    "Sungjae Im":                -0.60,
    "Harris English":            -0.70,
    "Lucas Glover":              -0.55,
    "Nick Taylor":               -0.75,
    "Akshay Bhatia":             -0.80,
    "Nicolai Hojgaard":          -0.70,
    "Davis Riley":               -0.65,
    "Brian Harman":              -0.80,
    "Jason Day":                 -1.10,
    "Sergio Garcia":             -0.70,
    "Adam Hadwin":               -0.50,
    "Christiaan Bezuidenhout":   -0.72,
    "Matthieu Pavon":            -0.62,
    "Joaquin Niemann":           -0.88,
    "Dean Burmester":            -0.48,
    "Rasmus Hojgaard":           -0.60,
    "Thriston Lawrence":         -0.52,
    "Kurt Kitayama":             -0.70,
    "Cam Davis":                 -0.58,
    "J.T. Poston":               -0.50,
    "Aaron Rai":                 -0.62,
    "Patrick Reed":              -0.82,
    "Zach Johnson":              -0.55,
    "Fred Couples":              -0.40,
    "Larry Mize":                -0.28,
    "José María Olazábal":       -0.35,
    "Taylor Moore":              -0.60,
    "Denny McCarthy":            -0.48,
    "Taylor Pendrith":           -0.65,
    "Wyndham Clark":             -0.85,
    "Chris Kirk":                -0.52,
    "Eric Cole":                 -0.72,
    "Emiliano Grillo":           -0.80,
    "Thomas Detry":              -0.78,
    "Alex Noren":                -0.65,
    "Ryan Fox":                  -0.58,
}
